---
- name: Set custom DNS in systemd-resolved
  hosts: target_linux_servers
  become: yes
  tasks:
    - name: Update systemd-resolved DNS settings
      lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: "^#?DNS="
        line: "DNS=8.8.8.8 1.1.1.1"
      notify: Restart systemd-resolved

  handlers:
    - name: Restart systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted

- name: Ensure /etc/resolv.conf is a symlink to systemd-resolved
  hosts: target_linux_servers
  become: yes
  tasks:
    - name: Remove existing /etc/resolv.conf (if not a symlink)
      file:
        path: /etc/resolv.conf
        state: absent
      when: not ansible_facts['os_family'] == "Windows"

    - name: Create symlink for resolv.conf
      file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link
