---
- name: Check for pending security updates
  hosts: target_linux_servers
  become: yes
  tasks:
    - name: Get list of available security updates
      shell: |
        apt list --upgradable 2>/dev/null | grep -i security | wc -l
      register: security_updates
      changed_when: false

    - name: Show number of pending security updates
      debug:
        msg: "Number of pending security updates: {{ security_updates.stdout }}"
