---
- name: Get current hostname
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get the hostname
      command: hostname
      register: hostname_output

    - name: Show the hostname
      debug:
        msg: "The current hostname is: {{ hostname_output.stdout }}"
