---
- name: Network Getting Started First Playbook
  hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: false

  tasks:
    - name: Get config for VyOS devices
      vyos.vyos.vyos_facts:
        gather_subset: min
      register: vyos_facts

    - name: Display the config
      ansible.builtin.debug:
        msg: >-
          The hostname is {{ vyos_facts.ansible_facts.ansible_net_hostname | default('Unknown') }} 
          and the OS is {{ vyos_facts.ansible_facts.ansible_net_version | default('Unknown') }}
