---
- name: Install net-tools on Linux servers
  hosts: target_linux_servers
  become: yes
  tasks:
    - name: Install net-tools on Debian-based systems
      apt:
        name: net-tools
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
