---
- name: Update and upgrade system
  hosts: target_linux_servers
  become: yes
  vars:
    reboot_ok: true  # Standardwert für die Reboot-Bedingung, falls nicht gesetzt
  tasks:
    - name: Run "apt-get update"
      apt:
        update_cache: yes

    - name: Run "apt-get dist-upgrade"
      apt:
        upgrade: dist

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Show reboot message if required
      debug:
        msg: "Reboot is required!!!"
      when: reboot_required.stat.exists

    - name: Reboot host(s) if required
      reboot:
        msg: "Rebooting system after updates"
        reboot_timeout: 600
      when: reboot_required.stat.exists and reboot_ok

    - name: Run "apt-get autoremove"
      apt:
        autoremove: yes
